# class_mapping.py

FOODSEG103_CLASSES = {
    "food_1": "candy",
    "food_2": "egg tart",
    "food_3": "french fries",
    "food_4": "chocolate",
    "food_5": "biscuit",
    "food_6": "popcorn",
    "food_7": "pudding",
    "food_8": "ice cream",
    "food_9": "cheese butter",
    "food_10": "cake",
    "food_11": "wine",
    "food_12": "milkshake",
    "food_13": "coffee",
    "food_14": "juice",
    "food_15": "milk",
    "food_16": "tea",
    "food_17": "almond",
    "food_18": "red beans",
    "food_19": "cashew",
    "food_20": "dried cranberries",
    "food_21": "soy",
    "food_22": "walnut",
    "food_23": "peanut",
    "food_24": "egg",
    "food_25": "apple",
    "food_26": "date",
    "food_27": "apricot",
    "food_28": "avocado",
    "food_29": "banana",
    "food_30": "strawberry",
    "food_31": "cherry",
    "food_32": "blueberry",
    "food_33": "raspberry",
    "food_34": "mango",
    "food_35": "olives",
    "food_36": "peach",
    "food_37": "lemon",
    "food_38": "pear",
    "food_39": "fig",
    "food_40": "pineapple",
    "food_41": "grape",
    "food_42": "kiwi",
    "food_43": "melon",
    "food_44": "orange",
    "food_45": "watermelon",
    "food_46": "steak",
    "food_47": "pork",
    "food_48": "chicken duck",
    "food_49": "sausage",
    "food_50": "fried meat",
    "food_51": "lamb",
    "food_52": "sauce",
    "food_53": "crab",
    "food_54": "fish",
    "food_55": "shellfish",
    "food_56": "shrimp",
    "food_57": "soup",
    "food_58": "bread",
    "food_59": "corn",
    "food_60": "hamburg",
    "food_61": "pizza",
    "food_62": "hanamaki baozi",
    "food_63": "wonton dumplings",
    "food_64": "pasta",
    "food_65": "noodles",
    "food_66": "rice",
    "food_67": "pie",
    "food_68": "tofu",
    "food_69": "eggplant",
    "food_70": "potato",
    "food_71": "garlic",
    "food_72": "cauliflower",
    "food_73": "tomato",
    "food_74": "kelp",
    "food_75": "seaweed",
    "food_76": "spring onion",
    "food_77": "rape",
    "food_78": "ginger",
    "food_79": "okra",
    "food_80": "lettuce",
    "food_81": "pumpkin",
    "food_82": "cucumber",
    "food_83": "white radish",
    "food_84": "carrot",
    "food_85": "asparagus",
    "food_86": "bamboo shoots",
    "food_87": "broccoli",
    "food_88": "celery stick",
    "food_89": "cilantro mint",
    "food_90": "snow peas",
    "food_91": "cabbage",
    "food_92": "bean sprouts",
    "food_93": "onion",
    "food_94": "pepper",
    "food_95": "green beans",
    "food_96": "French beans",
    "food_97": "king oyster mushroom",
    "food_98": "shiitake",
    "food_99": "enoki mushroom",
    "food_100": "oyster mushroom",
    "food_101": "white button mushroom",
    "food_102": "salad",
    "food_103": "other ingredients"
}